"""init 20 tables

Revision ID: 4159fea2c0ad
Revises: 
Create Date: 2026-08-19 14:04:06.756651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4159fea2c0ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('content', sa.String(length=512), nullable=False, comment='公告文案'),
    sa.Column('online_at', sa.DateTime(), nullable=True, comment='生效时间'),
    sa.Column('offline_at', sa.DateTime(), nullable=True, comment='失效时间'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='应聘职位（逻辑 FK→jobs.id）'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=32), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('intro', sa.String(length=1024), nullable=True, comment='个人简介'),
    sa.Column('attachment', sa.String(length=512), nullable=True, comment='简历附件 URL'),
    sa.Column('school', sa.String(length=128), nullable=True, comment='学校（校招）'),
    sa.Column('education', sa.String(length=32), nullable=True, comment='学历（校招）'),
    sa.Column('major', sa.String(length=128), nullable=True, comment='专业（校招）'),
    sa.Column('grad_at', sa.String(length=32), nullable=True, comment='毕业时间（校招）'),
    sa.Column('work_years', sa.Integer(), nullable=True, comment='工作年限（社招）'),
    sa.Column('current_title', sa.String(length=64), nullable=True, comment='当前职位（社招）'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='业务状态：pending/viewed/contacted/rejected'),
    sa.Column('processed_by', sa.BigInteger(), nullable=True, comment='处理人（逻辑 FK→users.id）'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job', 'applications', ['job_id'], unique=False)
    op.create_index('idx_phone', 'applications', ['phone'], unique=False)
    op.create_index('idx_processed', 'applications', ['processed_by'], unique=False)
    op.create_index('idx_status', 'applications', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=32), nullable=False, comment='手机号'),
    sa.Column('appointment_date', sa.Date(), nullable=False, comment='预约日期'),
    sa.Column('slot', sa.String(length=20), nullable=True, comment='时段'),
    sa.Column('note', sa.String(length=1024), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='业务状态：pending/contacted/done/cancelled'),
    sa.Column('processed_by', sa.BigInteger(), nullable=True, comment='处理人（逻辑 FK→users.id）'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date', 'appointments', ['appointment_date'], unique=False)
    op.create_index('idx_phone', 'appointments', ['phone'], unique=False)
    op.create_index('idx_processed', 'appointments', ['processed_by'], unique=False)
    op.create_index('idx_status', 'appointments', ['status'], unique=False)
    op.create_table('articles',
    sa.Column('title', sa.String(length=128), nullable=False, comment='标题'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类：company 企业新闻 / industry 行业资讯'),
    sa.Column('cover_image', sa.String(length=512), nullable=True, comment='封面图 URL'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='摘要'),
    sa.Column('body', mysql.LONGTEXT(), nullable=True, comment='正文（富文本 HTML）'),
    sa.Column('source', sa.String(length=128), nullable=True, comment='来源（转载标注）'),
    sa.Column('is_published', sa.Integer(), server_default='0', nullable=False, comment='是否发布 0/1'),
    sa.Column('is_top', sa.Integer(), server_default='0', nullable=False, comment='是否置顶/推荐 0/1'),
    sa.Column('publish_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('author', sa.String(length=64), nullable=True, comment='作者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category', 'articles', ['category'], unique=False)
    op.create_index('idx_publish', 'articles', ['publish_at'], unique=False)
    op.create_index('idx_published', 'articles', ['is_published'], unique=False)
    op.create_table('banners',
    sa.Column('image', sa.String(length=512), nullable=False, comment='图片 URL'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='标题'),
    sa.Column('subtitle', sa.String(length=255), nullable=True, comment='副标题'),
    sa.Column('link', sa.String(length=512), nullable=True, comment='跳转链接'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('online_at', sa.DateTime(), nullable=True, comment='生效时间'),
    sa.Column('offline_at', sa.DateTime(), nullable=True, comment='失效时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sort', 'banners', ['sort'], unique=False)
    op.create_table('case_products',
    sa.Column('case_id', sa.BigInteger(), nullable=False, comment='案例 id（逻辑 FK→cases.id）'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='产品 id（逻辑 FK→products.id）'),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('case_id', 'product_id')
    )
    op.create_index('idx_product', 'case_products', ['product_id'], unique=False)
    op.create_table('case_styles',
    sa.Column('name', sa.String(length=64), nullable=False, comment='字典值'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='style|space'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type', 'case_styles', ['type'], unique=False)
    op.create_table('cases',
    sa.Column('title', sa.String(length=128), nullable=False, comment='标题'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='客户实景/设计方案'),
    sa.Column('style', sa.String(length=32), nullable=True, comment='风格'),
    sa.Column('space', sa.String(length=32), nullable=True, comment='空间'),
    sa.Column('area', sa.String(length=32), nullable=True, comment='面积'),
    sa.Column('cover', sa.String(length=512), nullable=True, comment='封面'),
    sa.Column('gallery', mysql.JSON(), nullable=True, comment='图集'),
    sa.Column('background', mysql.LONGTEXT(), nullable=True, comment='项目背景'),
    sa.Column('description', mysql.LONGTEXT(), nullable=True, comment='设计说明'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type', 'cases', ['type'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=64), nullable=False, comment='空间分类名（客厅/卧室/书房/餐厅/全屋）'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sort', 'categories', ['sort'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.BigInteger(), server_default='0', nullable=False, comment='上级部门(0=顶级)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent', 'departments', ['parent_id'], unique=False)
    op.create_table('jobs',
    sa.Column('title', sa.String(length=128), nullable=False, comment='职位名'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='social 社会招聘 / campus 校园招聘'),
    sa.Column('dept', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('location', sa.String(length=64), nullable=True, comment='地点'),
    sa.Column('salary', sa.String(length=64), nullable=True, comment='薪资范围'),
    sa.Column('responsibility', mysql.LONGTEXT(), nullable=True, comment='岗位职责'),
    sa.Column('requirement', mysql.LONGTEXT(), nullable=True, comment='任职要求'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type', 'jobs', ['type'], unique=False)
    op.create_table('messages',
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('contact', sa.String(length=128), nullable=False, comment='联系方式'),
    sa.Column('content', sa.String(length=1024), nullable=False, comment='留言内容'),
    sa.Column('status', sa.String(length=20), server_default='unread', nullable=False, comment='业务状态：unread/read/done'),
    sa.Column('processed_by', sa.BigInteger(), nullable=True, comment='处理人（逻辑 FK→users.id）'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed', 'messages', ['processed_by'], unique=False)
    op.create_index('idx_status', 'messages', ['status'], unique=False)
    op.create_table('operation_logs',
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人 id（逻辑 FK→users.id）'),
    sa.Column('operator_name', sa.String(length=64), nullable=True, comment='操作人名称'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='动作编码'),
    sa.Column('object_type', sa.String(length=64), nullable=True, comment='对象类型'),
    sa.Column('object_id', sa.BigInteger(), nullable=True, comment='对象 id'),
    sa.Column('detail', sa.String(length=1024), nullable=True, comment='详情'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='来源 IP'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action', 'operation_logs', ['action'], unique=False)
    op.create_index('idx_created', 'operation_logs', ['created_date'], unique=False)
    op.create_index('idx_operator', 'operation_logs', ['operator_id'], unique=False)
    op.create_table('pages',
    sa.Column('key', sa.String(length=32), nullable=False, comment='about|history|brand|contact'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='页面标题'),
    sa.Column('content', mysql.LONGTEXT(), nullable=True, comment='富文本内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_key', 'pages', ['key'], unique=True)
    op.create_table('products',
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='所属空间分类（逻辑 FK→categories.id）'),
    sa.Column('series', sa.String(length=64), nullable=False, comment='所属系列（如：胡桃木）'),
    sa.Column('product_code', sa.String(length=64), nullable=False, comment='产品编号'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='产品名'),
    sa.Column('description', mysql.LONGTEXT(), nullable=True, comment='产品描述（富文本）'),
    sa.Column('spec_params', mysql.JSON(), nullable=True, comment='规格参数（JSON 串）'),
    sa.Column('cover_image', sa.String(length=512), nullable=True, comment='封面图片 URL'),
    sa.Column('gallery', mysql.JSON(), nullable=True, comment='其它图片 URL（JSON 串）'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='发布状态：on 上架 / off 下架 / draft 草稿'),
    sa.Column('is_top', sa.Integer(), server_default='0', nullable=False, comment='是否置顶 0/1'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_series', 'products', ['series'], unique=False)
    op.create_index('idx_sort', 'products', ['sort'], unique=False)
    op.create_index('idx_status', 'products', ['status'], unique=False)
    op.create_index('uk_product_code', 'products', ['product_code'], unique=True)
    op.create_table('reviews',
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像 URL'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='客户姓名'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('house', sa.String(length=64), nullable=True, comment='户型'),
    sa.Column('rating', sa.Integer(), server_default='5', nullable=False, comment='评分 1-5'),
    sa.Column('content', sa.String(length=512), nullable=True, comment='评价内容'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='chk_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('permissions', mysql.JSON(), nullable=True, comment='权限编码集合(RBAC)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_steps',
    sa.Column('step_no', sa.Integer(), nullable=False, comment='步骤序号 1-4'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='步骤标题'),
    sa.Column('desc', sa.String(length=512), nullable=True, comment='步骤说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_config',
    sa.Column('address', sa.String(length=255), nullable=True, comment='体验中心地址'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='客服电话'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='联系邮箱'),
    sa.Column('hours', sa.String(length=64), nullable=True, comment='营业时间'),
    sa.Column('map_coord', sa.String(length=64), nullable=True, comment='地图坐标'),
    sa.Column('appointment_slots', mysql.JSON(), nullable=True, comment='预约时段选项'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名（登录名，唯一）'),
    sa.Column('real_name', sa.String(length=64), nullable=True, comment='姓名'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('gender', sa.Integer(), server_default='0', nullable=False, comment='性别 0未知/1男/2女'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='岗位'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门编号（逻辑 FK→departments.id）'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色编号（逻辑 FK→roles.id）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='登录密码(bcrypt)'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近登录时间'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像 URL（BR-1.4 上传，后台顶栏展示）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Integer(), server_default='1', nullable=False, comment='1激活/0禁用'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建人(用户id)'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='修改人(用户id)'),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dept', 'users', ['dept_id'], unique=False)
    op.create_index('idx_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_role', 'users', ['role_id'], unique=False)
    op.create_index('uk_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_username', table_name='users')
    op.drop_index('idx_role', table_name='users')
    op.drop_index('idx_phone', table_name='users')
    op.drop_index('idx_dept', table_name='users')
    op.drop_table('users')
    op.drop_table('site_config')
    op.drop_table('service_steps')
    op.drop_table('roles')
    op.drop_table('reviews')
    op.drop_index('uk_product_code', table_name='products')
    op.drop_index('idx_status', table_name='products')
    op.drop_index('idx_sort', table_name='products')
    op.drop_index('idx_series', table_name='products')
    op.drop_index('idx_category', table_name='products')
    op.drop_table('products')
    op.drop_index('uk_key', table_name='pages')
    op.drop_table('pages')
    op.drop_index('idx_operator', table_name='operation_logs')
    op.drop_index('idx_created', table_name='operation_logs')
    op.drop_index('idx_action', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('idx_status', table_name='messages')
    op.drop_index('idx_processed', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_type', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_parent', table_name='departments')
    op.drop_table('departments')
    op.drop_index('idx_sort', table_name='categories')
    op.drop_table('categories')
    op.drop_index('idx_type', table_name='cases')
    op.drop_table('cases')
    op.drop_index('idx_type', table_name='case_styles')
    op.drop_table('case_styles')
    op.drop_index('idx_product', table_name='case_products')
    op.drop_table('case_products')
    op.drop_index('idx_sort', table_name='banners')
    op.drop_table('banners')
    op.drop_index('idx_published', table_name='articles')
    op.drop_index('idx_publish', table_name='articles')
    op.drop_index('idx_category', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_status', table_name='appointments')
    op.drop_index('idx_processed', table_name='appointments')
    op.drop_index('idx_phone', table_name='appointments')
    op.drop_index('idx_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('idx_status', table_name='applications')
    op.drop_index('idx_processed', table_name='applications')
    op.drop_index('idx_phone', table_name='applications')
    op.drop_index('idx_job', table_name='applications')
    op.drop_table('applications')
    op.drop_table('announcements')
    # ### end Alembic commands ###
