"""add_banner_images

Revision ID: fdb936d935c0
Revises: 4159fea2c0ad
Create Date: 2026-08-20 18:02:16.666899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fdb936d935c0'
down_revision: Union[str, Sequence[str], None] = '4159fea2c0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('images', mysql.JSON(), nullable=True, comment='轮播多图 URL 列表（首页轮播展示，兼容 image 单图）'))
    op.alter_column('jobs', 'cover_image',
               existing_type=mysql.VARCHAR(length=512),
               comment='配图 URL（前台加入我们卡片展示）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'cover_image',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='配图 URL（前台加入我们卡片展示）',
               existing_nullable=True)
    op.drop_column('banners', 'images')
    # ### end Alembic commands ###
